apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: telecom-order-to-activate-locations
  description: Telecom Order-to-Activate OSS/BSS integration topology (impact-analysis sample)
  annotations:
    backstage.io/techdocs-ref: dir:.
  tibco.developer.hub/topology:
    theme:
      name: blue
    entityIcon:
      icon: Hub
      iconTooltip: Telecom Order-to-Activate Location
spec:
  targets:
    - ./foundation.yaml
    - ./infrastructure.yaml
    - ./messages.yaml
    - ./integration-apps.yaml
