apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "tibco-developer-hub-mcp-120"
  title: TIBCO Developer Hub MCP Server
  description: MCP server for TIBCO Developer Hub.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - model-context-protocol
spec:
  type: mcp-server
  lifecycle: production
  owner: TIBCO
  remotes:
    - type: streamable-http
      url: /api/mcp-actions/v1
  definition:
    $text: ./backstage-mcp-definition.yaml
