apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "tibco-platform-api-120"
  description: "API of the TIBCO Platform (1.20)"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - tibco-platform
    - platform
    - core
spec:
  type: openapi
  lifecycle: production
  owner: TIBCO
  definition:
    $text: ./control-plane-api-120.json
