apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "tibco-platform-mcp-120"
  title: TIBCO Control Plane MCP Server
  description: MCP server for the TIBCO Control Plane.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - model-context-protocol
spec:
  type: mcp-server
  lifecycle: production
  owner: TIBCO
  remotes:
    - type: streamable-http
      url: /cp/mcp
  definition:
    $text: ./control-plane-mcp-definition-120.yaml
